server {
    listen 80;
    server_name localhost;
    
    # Directorio donde pondremos tus archivos compilados
    root /usr/share/nginx/html;
    
    # Archivo de entrada
    index index.html;

    # ESTA REGLA ES LA MÁS IMPORTANTE PARA ANGULAR:
    # Si la ruta solicitada no es un archivo real ($uri),
    # redirige todo al index.html. Esto permite que el Routing de Angular funcione.
    location / {
        try_files $uri $uri/ /index.html;
    }
    
    # Opcional: Configuración de caché para archivos estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}