server.port=8080
spring.application.name=auth-gateway-service

# Base de datos
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db_auth}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:orscon}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Security
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Gateway Configuration (URLs din�micas)
gateway.genomics.url=${GENOMICS_URL:http://localhost:3000/api/v1}
gateway.clinical.url=${CLINICAL_URL:http://localhost:3001/api/v1}