apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  # "rootpassword" en Base64 es "cm9vdHBhc3N3b3Jk"
  # Puedes generar otros con: echo -n "tu_pass" | base64
  mysql-root-password: cm9vdHBhc3N3b3Jk
  mysql-user: cm9vdA== # "root"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Base de Datos
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  
  # Nombres de Bases de Datos
  DB_NAME_GENOMICA: "db_genomica"
  DB_NAME_CLINICA: "db_clinica"
  DB_NAME_AUTH: "db_auth"
  
  # URLs Internas (Usamos nombres de Servicio K8s y puerto 80)
  # El Gateway usará esto para encontrar a los otros pods
  GENOMICS_URL: "http://genomica-service:80/api/v1"
  CLINICAL_URL: "http://clinica-service:80/api/v1"