# Development docker-compose file
# This file will run the app in development mode
# ${} are environment variables that will be replaced
# with the values in the .env file
services:
  # App service
  # This service will run the application
  clinical:
    # Image to use
    # Change <app name> with the name of the app
    image: img-clinical-dev:latest

    # Environment file to use
    env_file:
      - ./clinica-nestjs/dev.env

    # Environment variables
    environment:
      NODE_ENV: ${CLINICA_NODE_ENV}

    # Container name
    # Used to identify the container
    # Also to communicate with other containers
    container_name: ${CLINICA_HOST_NAME}

    # Build the app using the previously created
    # Dockerfile
    build:
      context: clinica-nestjs
      dockerfile: Dockerfile.dev

    # Volume to mount the source code
    # This will allow the app to be updated
    # without the need to rebuild the container
    volumes:
      - ./clinica-nestjs/src:/app/src

    # Port forwarding:
    # This will allow the app to be accessed from
    # the host machine.
    # Change <host port> with the port that the app
    # will use in the host machine
    ports:
      - "3000:${CLINICA_PORT}"