# Generated by Django 5.2.8 on 2025-11-21 06:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Ej: BRCA1', max_length=50, unique=True)),
                ('full_name', models.CharField(help_text='Nombre completo del gen', max_length=255)),
                ('function_summary', models.TextField(help_text='Resumen de la función del gen')),
            ],
        ),
        migrations.CreateModel(
            name='GeneticVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chromosome', models.CharField(help_text='Ej: chr17', max_length=10)),
                ('position', models.BigIntegerField(help_text='Posición genómica')),
                ('reference_base', models.CharField(help_text='Ej: A', max_length=255)),
                ('alternate_base', models.CharField(help_text='Ej: G', max_length=255)),
                ('impact', models.CharField(help_text='Consecuencia de la variante', max_length=50)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.gene')),
            ],
        ),
    ]
