# Generated by Django 5.2.8 on 2025-11-21 06:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVariantReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_id', models.UUIDField(help_text='UUID del paciente (Validado vía API Clínica)')),
                ('detection_date', models.DateField(auto_now_add=True)),
                ('allele_frequency', models.DecimalField(decimal_places=4, help_text='VAF (Variant Allele Frequency) ej: 0.1500', max_digits=5)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.geneticvariant')),
            ],
        ),
    ]
